#!/bin/bash
echo "Setting up Universal Tagging Bot..."
echo ""
echo "1. Make sure you have Python 3.8+ installed"
echo "2. Create virtual environment: python -m venv venv"
echo "3. Activate it: source venv/bin/activate"
echo "4. Install dependencies: pip install -r requirements.txt"
echo "5. Run the bot: python bot.py"
echo ""
echo "For production deployment:"
echo "1. Revoke the current bot token in @BotFather"
echo "2. Create new bot token"
echo "3. Set environment variable: TELEGRAM_BOT_TOKEN"
echo "4. Deploy to Heroku with the Procfile"
